image: atlassian/default-image:4

definitions:
  steps:
    - step: &sync-with-github
        name: Sync with Github
        clone:
          enabled: false
        script:
            - git clone --bare git@bitbucket.org:fmisrl/fmi-packages.git
            - cd fmi-packages.git
            - git push --mirror git@github.com:fmisrl/mongo-dbcontext.git

  
pipelines:  
  default:
    - step: *sync-with-github
