using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using FmiSrl.MongoDbContext.SourceGenerator.Models;
using Microsoft.CodeAnalysis;

namespace FmiSrl.MongoDbContext.SourceGenerator.Generation;

internal static class DbContextEmitter
{
    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public static string Emit(DbContextModel model)
    {
        var builder = new StringBuilder();
        using var writer = new IndentedTextWriter(new StringWriter(builder));

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("using MongoDB.Bson.Serialization;");
        writer.WriteLine("using MongoDB.Driver;");
        writer.WriteLine();
        var hasNamespace = !string.IsNullOrWhiteSpace(model.Namespace);
        if (hasNamespace)
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        if (!string.IsNullOrWhiteSpace(model.ClassModifiers))
        {
            writer.Write(model.ClassModifiers.Trim());
            writer.Write(" ");
        }

        writer.Write("class ");
        writer.Write(model.ClassName);
        writer.Write(" : global::FmiSrl.MongoDbContext.Abstractions.BsonDbContext<");
        writer.Write(model.ClassName);
        writer.Write(">, ");
        writer.WriteLine(model.InterfaceSymbol.ToDisplayString(FullyQualifiedFormat));
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var collection in model.Collections)
        {
            writer.Write("public ");
            writer.Write(collection.CollectionType.ToDisplayString(FullyQualifiedFormat));
            writer.Write(" ");
            writer.Write(collection.PropertyName);
            writer.Write(" => Database.GetCollection<");
            writer.Write(collection.DocumentType.ToDisplayString(FullyQualifiedFormat));
            writer.Write(">(");
            writer.Write(collection.CollectionNameLiteral);
            writer.WriteLine(");");
            writer.WriteLine();
        }

        writer.WriteLine("protected override string GetCollectionName<T>()");
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var collection in model.Collections)
        {
            writer.Write("if(typeof(T) == typeof(");
            writer.Write(collection.DocumentType.ToDisplayString(FullyQualifiedFormat));
            writer.WriteLine("))");
            writer.WriteLine("{");
            writer.Indent++;
            writer.Write("return ");
            writer.Write(collection.CollectionNameLiteral);
            writer.WriteLine(";");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.WriteLine("throw new System.NotSupportedException($\"Unsupported type {typeof(T)}\");");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("public override IMongoCollection<T> GetCollectionFromType<T>()");
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var collection in model.Collections)
        {
            writer.Write("if(typeof(T) == typeof(");
            writer.Write(collection.DocumentType.ToDisplayString(FullyQualifiedFormat));
            writer.WriteLine("))");
            writer.WriteLine("{");
            writer.Indent++;
            writer.Write("return (IMongoCollection<T>)this.");
            writer.Write(collection.PropertyName);
            writer.WriteLine(";");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.WriteLine("throw new System.NotSupportedException($\"Unsupported type {typeof(T)}\");");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("protected override void InitializeDatabase()");
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var collection in model.Collections)
        {
            writer.Write("if(!RegisteredMaps.Contains(nameof(");
            writer.Write(collection.DocumentType.ToDisplayString(FullyQualifiedFormat));
            writer.WriteLine(")))");
            writer.WriteLine("{");
            writer.Indent++;
            writer.Write("RegisterMap<");
            writer.Write(collection.DocumentType.ToDisplayString(FullyQualifiedFormat));
            writer.WriteLine(">();");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        if (hasNamespace)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        return builder.ToString();
    }
}
