name: Build, test and publish
on:
  - push

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        mongodb-version: ['7.0', '8.0']
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET ${{ matrix.dotnet-version }}.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: false
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: mongoadmin
          mongodb-password: mysupersecretpassword
      
      - name: Build and restore projects
        run: dotnet build FmiSrl.MongoDbContext.sln --configuration Release
        
      - name: Test projects
        env:
          ConnectionStrings__Default: mongodb://mongoadmin:mysupersecretpassword@localhost:27017/?connectTimeoutMS=6000
        run: dotnet test FmiSrl.MongoDbContext.sln --no-build --configuration Release --logger trx --results-directory "TestResults-mongodb${{ matrix.mongodb-version }}"
      
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-mongodb${{ matrix.mongodb-version }}
          path: TestResults-mongodb${{ matrix.mongodb-version }}

        if: ${{ always() }}
        
  publish:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: false

      - name: Build
        run: dotnet build FmiSrl.MongoDbContext.sln --configuration Release
        
      - name: Pack
        run: dotnet pack FmiSrl.MongoDbContext.sln --configuration Release -o out
        
      - name: Upload to Nuget
        run: dotnet nuget push out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
      - name: Upload to GPR
        run: dotnet nuget push out/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/fmisrl/index.json
